language: node_js
node_js:
  - '0.12'
sudo: false
env:
  matrix:
    - GROUP=
  global:
    - GHREPO=github.com/phosphorjs/phosphor-panel
    - secure: TQa2unD7KCY1Ni+EDvOdrYcuGr7u5wGSYeqtRwkzm0ljwPcYMVxiBPYkMvizD3rIDTieeuwnAARYv+2WsRRBnjDopstj9BKDfIXQMQlA5VM+sc6JVGbuXohoIVPLLsAk8RF8iVYLwTgGMjPpXIoAXLjazTCySUGFr/c4cDCuXiLTFoIruHANbAkDmNKsEVva/yDZShMadAGmYSy8RNbd9uxfgm7jY2qPSock2cr/qmL99Qqlyd8AiHS6drs4WvB4ej0O3Ri6WZdXkQGQOo3K5IOgfGOtyUCgF2EerxuWRgBVDSW/BW8ja94sqXA8lEPDbgF2CzXeOIYFJet2+n+HAKEbzt8xXOOEUbO6svTyd71jiUcRYOQXXkcio6F33+91aG/OrTM0GHKvlplBOWYm1MQ2PFhnWOn7CQx+Z3aScZAja4B8jAuN/3ZT4bWwn8RTZnlxD9BYW1Pu8o2v1eQDRCsiSm99imAIQ+C4i9Yh+yUILZZJoOy3aLpKPwOkoRPcJy4x1+xHb6USm0D/DNCmo0aOp4wXD/ujpdxyRwZRpTw9e60wvHRpqP9DBChachkfJqT1wHsOJesXpYCcXOBUC3JxS4eIn5cF2oetl4ilnt0nZogkAKwwdvbvXF3q473fFbJTQ5NTYfmJpky9FJ2zfctyzMIYqVL70lbAxtzhGPs=
install:
  - bash ./scripts/travis_install.sh
script:
  - bash ./scripts/travis_script.sh
after_success:
  - bash ./scripts/travis_after_success.sh
